/**
 * v1.12.0 — curated MCP registry signature verification.
 *
 * Closes a finding from the v1.x security audit: the curated registry
 * was fetched over HTTPS but never cryptographically verified, so any
 * compromise of the GitHub raw CDN (or an MITM that defeated cert
 * pinning) could inject malicious `npx` install commands into the
 * marketplace. Now: each fetched registry.json is paired with a
 * detached Ed25519 signature over its SHA-256 hash. We verify the
 * signature against the bundled public key and refuse to surface the
 * "Verified" badge on entries whose registry didn't verify.
 *
 * Threat model — what this protects against:
 *  - GitHub raw CDN compromise / MITM tampering with registry.json
 *    in transit (sig verification fails, fall back to bundled).
 *  - A different process on the user\'s machine swapping the bundled
 *    registry.json (sig file would need to be regenerated by us, and
 *    the public key is in compiled JS so swapping it requires app
 *    re-signing — much higher bar than swapping a JSON file).
 *
 * What this does NOT protect against:
 *  - Malicious upstream npm packages — an `npx evil-package` install
 *    in a curated entry is still evil even with a valid signature.
 *    That\'s a supply-chain problem signature verification can\'t
 *    solve. Future: npm package signature verification via sigstore.
 *  - A determined attacker with control over our private signing key.
 *    Kept off the repo + off CI for now; future hardening could move
 *    it into a hardware key.
 *
 * Why Ed25519 not RSA: smaller signatures, faster verification, modern
 * default. Already supported by Node\'s built-in crypto module (no
 * dependency needed). The 64-byte signature comfortably fits beside
 * registry.json.
 */
import { createPublicKey, createHash, verify } from 'node:crypto'
import { log } from '../logger'

/**
 * Public verification key for the curated MCP registry. Ed25519 SPKI in
 * base64. The matching private key lives off-repo at
 * mcp-registry/.private-key.b64 (gitignored) — used by
 * scripts/sign-mcp-registry.mjs to produce signature.json.
 *
 * Rotation: re-run the sign script to generate a new keypair, replace
 * this constant with the new public key, re-sign registry.json. Old
 * builds with the old public key won\'t verify the new registry —
 * which is fine, they\'ll fall back to the bundled-only path.
 */
const CURATED_PUBLIC_KEY_SPKI_BASE64 =
  'MCowBQYDK2VwAyEAHPBYiWgwZnym4IgMSYXYjZPqazj+sTx+KIFqrQsGN0I='

/** Cached parsed public key. createPublicKey allocates; we do it once. */
let publicKeyCache: ReturnType<typeof createPublicKey> | null = null

function getPublicKey(): ReturnType<typeof createPublicKey> {
  if (publicKeyCache) return publicKeyCache
  publicKeyCache = createPublicKey({
    key: Buffer.from(CURATED_PUBLIC_KEY_SPKI_BASE64, 'base64'),
    format: 'der',
    type: 'spki'
  })
  return publicKeyCache
}

/** Shape of the `signature.json` companion file. Versioned so a future
 *  signature scheme change (different curve, hash algorithm bundle)
 *  can coexist with old builds. */
export interface RegistrySignatureFile {
  version: number
  algorithm: 'ed25519'
  /** SHA-256 hex digest of the canonical registry.json bytes. */
  registrySha256: string
  /** Base64-encoded Ed25519 signature over registrySha256 (the bytes,
   *  not the hex string — see verifyRegistrySignature for details). */
  signature: string
  /** ISO-8601 timestamp of when the signature was produced. Surfaced
   *  in logs so a stale signature is easy to spot. */
  signedAt: string
}

/**
 * Verifies a fetched registry against its signature file. Returns true
 * on success, false on any failure (bad JSON, hash mismatch, signature
 * verification failed, missing fields). Never throws — caller treats a
 * false return as "registry is unverified" and downgrades the trust UI
 * accordingly.
 *
 * Source param is used only for the log line so we can distinguish
 * "bundled signature broke" (we shipped a bad pairing) from "remote
 * signature broke" (potentially in-transit tampering).
 */
export function verifyRegistrySignature(
  registryText: string,
  signatureText: string,
  source: 'remote' | 'bundled'
): boolean {
  let sigFile: RegistrySignatureFile
  try {
    sigFile = JSON.parse(signatureText) as RegistrySignatureFile
  } catch {
    log('warn', 'system', `MCP registry signature (${source}): companion JSON did not parse.`)
    return false
  }
  if (sigFile.algorithm !== 'ed25519') {
    log(
      'warn',
      'system',
      `MCP registry signature (${source}): unsupported algorithm "${sigFile.algorithm}"; expected ed25519.`
    )
    return false
  }
  // Recompute the SHA-256 of the registry bytes EXACTLY as fetched —
  // any whitespace / encoding drift between our compute step and the
  // sign step would flip the hash. Keep the text raw on both sides.
  const expectedHash = sigFile.registrySha256
  const actualHash = createHash('sha256').update(registryText, 'utf8').digest('hex')
  if (expectedHash !== actualHash) {
    log(
      'warn',
      'system',
      `MCP registry signature (${source}): SHA-256 mismatch. expected=${expectedHash} actual=${actualHash}. Possible tampering or whitespace drift since sign-time.`
    )
    return false
  }
  // Verify the Ed25519 signature against the raw hash bytes (NOT the
  // hex string — signing the hex string would double-encode). The sign
  // script must use the same byte form.
  let signatureBytes: Buffer
  try {
    signatureBytes = Buffer.from(sigFile.signature, 'base64')
  } catch {
    log('warn', 'system', `MCP registry signature (${source}): signature is not valid base64.`)
    return false
  }
  const hashBytes = Buffer.from(actualHash, 'hex')
  let isValid = false
  try {
    isValid = verify(null, hashBytes, getPublicKey(), signatureBytes)
  } catch (err) {
    log(
      'warn',
      'system',
      `MCP registry signature (${source}): verify() threw — likely key/sig format mismatch.`,
      err instanceof Error ? err.message : String(err)
    )
    return false
  }
  if (!isValid) {
    log(
      'warn',
      'system',
      `MCP registry signature (${source}): Ed25519 verification failed. Refusing to mark entries as Verified.`
    )
    return false
  }
  log(
    'info',
    'system',
    `MCP registry signature (${source}): verified OK (signed ${sigFile.signedAt}).`
  )
  return true
}
