/**
 * Embedded Python runner script.
 *
 * Written to disk on first kernel boot (one shared copy per app install)
 * and executed by `python` / `python3`. Reads NDJSON requests from stdin,
 * writes NDJSON responses to stdout, maintains a per-process globals dict
 * so variables / imports / files persist across exec calls.
 *
 * Why we don't ship a real Jupyter kernel:
 *   - Requires ipykernel + jupyter_client on every user's machine.
 *   - ZMQ socket setup is fiddly cross-platform.
 *   - The thing we actually need (stateful exec + stdout capture) is 30
 *     lines of Python. We can always swap to jupyter_client later if a
 *     user demands display() / rich outputs / kernel debug protocol.
 *
 * Protocol (one JSON object per line, both directions):
 *
 *   stdin  → {"id": "req-1", "type": "exec", "code": "x = 1"}
 *          → {"id": "req-2", "type": "shutdown"}
 *
 *   stdout ← {"id": "req-1", "type": "done",
 *             "stdout": "...", "stderr": "...", "error": null}
 *          ← {"id": "ready",  "type": "ready"}        (on startup)
 *
 * `error` carries a traceback string when the user code raised; null on
 * clean success. SystemExit and KeyboardInterrupt are caught explicitly
 * so the kernel survives a Stop click without dying.
 *
 * The script is kept here (not as a .py file) so the build pipeline
 * doesn't have to copy assets — everything ships in the bundled JS.
 */
export const PYTHON_RUNNER_SOURCE = String.raw`# AUTOGENERATED — do not edit; source lives in runner.ts
import sys, json, io, traceback, os
from contextlib import redirect_stdout, redirect_stderr

# Per-process globals — survive across exec() calls. Seeded with __name__
# so user code reads like a real script (e.g. "if __name__ == '__main__'").
GLOBALS = {'__name__': '__main__', '__builtins__': __builtins__}

def emit(obj):
    sys.stdout.write(json.dumps(obj) + '\n')
    sys.stdout.flush()

def run_exec(req):
    rid = req.get('id', '')
    code = req.get('code', '')
    out = io.StringIO()
    err = io.StringIO()
    error_text = None
    try:
        with redirect_stdout(out), redirect_stderr(err):
            compiled = compile(code, '<cell>', 'exec')
            exec(compiled, GLOBALS)
    except SystemExit as exc:
        error_text = f'SystemExit({exc.code})'
    except KeyboardInterrupt:
        error_text = 'KeyboardInterrupt'
    except BaseException:
        error_text = traceback.format_exc()
    emit({
        'id': rid,
        'type': 'done',
        'stdout': out.getvalue(),
        'stderr': err.getvalue(),
        'error': error_text,
        'cwd': os.getcwd(),
    })

def main():
    # Announce readiness so the parent process knows the kernel survived
    # startup (catches missing-module-on-PATH races). Includes the active
    # Python version + interpreter path for the Settings panel.
    emit({
        'id': 'ready',
        'type': 'ready',
        'python': sys.version.split()[0],
        'executable': sys.executable,
    })
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            req = json.loads(line)
        except Exception:
            continue
        kind = req.get('type')
        if kind == 'shutdown':
            return
        if kind == 'exec':
            run_exec(req)

if __name__ == '__main__':
    try:
        main()
    except BrokenPipeError:
        # Parent dropped stdin/stdout; exit cleanly so we don't dump a
        # traceback into orphaned pipes.
        pass
`
